// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PyModuleProt.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PyModuleProt_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PyModuleProt_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PyModuleProt_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PyModuleProt_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PyModuleProt_2eproto;
namespace PyModuleProt {
class DataPacket;
struct DataPacketDefaultTypeInternal;
extern DataPacketDefaultTypeInternal _DataPacket_default_instance_;
class SendCommand;
struct SendCommandDefaultTypeInternal;
extern SendCommandDefaultTypeInternal _SendCommand_default_instance_;
}  // namespace PyModuleProt
PROTOBUF_NAMESPACE_OPEN
template<> ::PyModuleProt::DataPacket* Arena::CreateMaybeMessage<::PyModuleProt::DataPacket>(Arena*);
template<> ::PyModuleProt::SendCommand* Arena::CreateMaybeMessage<::PyModuleProt::SendCommand>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace PyModuleProt {

enum Command : int {
  COMMAND_NOOP = 0,
  COMMAND_START_STREAM = 1,
  COMMAND_STOP_STREAM = 2,
  Command_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Command_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Command_IsValid(int value);
constexpr Command Command_MIN = COMMAND_NOOP;
constexpr Command Command_MAX = COMMAND_STOP_STREAM;
constexpr int Command_ARRAYSIZE = Command_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Command_descriptor();
template<typename T>
inline const std::string& Command_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Command>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Command_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Command_descriptor(), enum_t_value);
}
inline bool Command_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Command* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Command>(
    Command_descriptor(), name, value);
}
enum State : int {
  STATE_IDLE = 0,
  STATE_STREAMING = 1,
  STATE_ERROR = 2,
  State_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  State_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool State_IsValid(int value);
constexpr State State_MIN = STATE_IDLE;
constexpr State State_MAX = STATE_ERROR;
constexpr int State_ARRAYSIZE = State_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* State_descriptor();
template<typename T>
inline const std::string& State_Name(T enum_t_value) {
  static_assert(::std::is_same<T, State>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function State_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    State_descriptor(), enum_t_value);
}
inline bool State_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, State* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<State>(
    State_descriptor(), name, value);
}
// ===================================================================

class DataPacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PyModuleProt.DataPacket) */ {
 public:
  inline DataPacket() : DataPacket(nullptr) {}
  ~DataPacket() override;
  explicit PROTOBUF_CONSTEXPR DataPacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DataPacket(const DataPacket& from);
  DataPacket(DataPacket&& from) noexcept
    : DataPacket() {
    *this = ::std::move(from);
  }

  inline DataPacket& operator=(const DataPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline DataPacket& operator=(DataPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DataPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const DataPacket* internal_default_instance() {
    return reinterpret_cast<const DataPacket*>(
               &_DataPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DataPacket& a, DataPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(DataPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DataPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DataPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DataPacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DataPacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DataPacket& from) {
    DataPacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DataPacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PyModuleProt.DataPacket";
  }
  protected:
  explicit DataPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampFieldNumber = 2,
    kStateFieldNumber = 1,
    kSomeSensorFieldNumber = 3,
  };
  // string timestamp = 2;
  void clear_timestamp();
  const std::string& timestamp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_timestamp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_timestamp();
  PROTOBUF_NODISCARD std::string* release_timestamp();
  void set_allocated_timestamp(std::string* timestamp);
  private:
  const std::string& _internal_timestamp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(const std::string& value);
  std::string* _internal_mutable_timestamp();
  public:

  // .PyModuleProt.State state = 1;
  void clear_state();
  ::PyModuleProt::State state() const;
  void set_state(::PyModuleProt::State value);
  private:
  ::PyModuleProt::State _internal_state() const;
  void _internal_set_state(::PyModuleProt::State value);
  public:

  // int32 some_sensor = 3;
  void clear_some_sensor();
  int32_t some_sensor() const;
  void set_some_sensor(int32_t value);
  private:
  int32_t _internal_some_sensor() const;
  void _internal_set_some_sensor(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PyModuleProt.DataPacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr timestamp_;
    int state_;
    int32_t some_sensor_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PyModuleProt_2eproto;
};
// -------------------------------------------------------------------

class SendCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PyModuleProt.SendCommand) */ {
 public:
  inline SendCommand() : SendCommand(nullptr) {}
  ~SendCommand() override;
  explicit PROTOBUF_CONSTEXPR SendCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendCommand(const SendCommand& from);
  SendCommand(SendCommand&& from) noexcept
    : SendCommand() {
    *this = ::std::move(from);
  }

  inline SendCommand& operator=(const SendCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendCommand& operator=(SendCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendCommand* internal_default_instance() {
    return reinterpret_cast<const SendCommand*>(
               &_SendCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SendCommand& a, SendCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(SendCommand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SendCommand& from) {
    SendCommand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendCommand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PyModuleProt.SendCommand";
  }
  protected:
  explicit SendCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // .PyModuleProt.Command command = 1;
  void clear_command();
  ::PyModuleProt::Command command() const;
  void set_command(::PyModuleProt::Command value);
  private:
  ::PyModuleProt::Command _internal_command() const;
  void _internal_set_command(::PyModuleProt::Command value);
  public:

  // optional int32 value = 2;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  int32_t value() const;
  void set_value(int32_t value);
  private:
  int32_t _internal_value() const;
  void _internal_set_value(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PyModuleProt.SendCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    int command_;
    int32_t value_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PyModuleProt_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DataPacket

// .PyModuleProt.State state = 1;
inline void DataPacket::clear_state() {
  _impl_.state_ = 0;
}
inline ::PyModuleProt::State DataPacket::_internal_state() const {
  return static_cast< ::PyModuleProt::State >(_impl_.state_);
}
inline ::PyModuleProt::State DataPacket::state() const {
  // @@protoc_insertion_point(field_get:PyModuleProt.DataPacket.state)
  return _internal_state();
}
inline void DataPacket::_internal_set_state(::PyModuleProt::State value) {
  
  _impl_.state_ = value;
}
inline void DataPacket::set_state(::PyModuleProt::State value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:PyModuleProt.DataPacket.state)
}

// string timestamp = 2;
inline void DataPacket::clear_timestamp() {
  _impl_.timestamp_.ClearToEmpty();
}
inline const std::string& DataPacket::timestamp() const {
  // @@protoc_insertion_point(field_get:PyModuleProt.DataPacket.timestamp)
  return _internal_timestamp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DataPacket::set_timestamp(ArgT0&& arg0, ArgT... args) {
 
 _impl_.timestamp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PyModuleProt.DataPacket.timestamp)
}
inline std::string* DataPacket::mutable_timestamp() {
  std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:PyModuleProt.DataPacket.timestamp)
  return _s;
}
inline const std::string& DataPacket::_internal_timestamp() const {
  return _impl_.timestamp_.Get();
}
inline void DataPacket::_internal_set_timestamp(const std::string& value) {
  
  _impl_.timestamp_.Set(value, GetArenaForAllocation());
}
inline std::string* DataPacket::_internal_mutable_timestamp() {
  
  return _impl_.timestamp_.Mutable(GetArenaForAllocation());
}
inline std::string* DataPacket::release_timestamp() {
  // @@protoc_insertion_point(field_release:PyModuleProt.DataPacket.timestamp)
  return _impl_.timestamp_.Release();
}
inline void DataPacket::set_allocated_timestamp(std::string* timestamp) {
  if (timestamp != nullptr) {
    
  } else {
    
  }
  _impl_.timestamp_.SetAllocated(timestamp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PyModuleProt.DataPacket.timestamp)
}

// int32 some_sensor = 3;
inline void DataPacket::clear_some_sensor() {
  _impl_.some_sensor_ = 0;
}
inline int32_t DataPacket::_internal_some_sensor() const {
  return _impl_.some_sensor_;
}
inline int32_t DataPacket::some_sensor() const {
  // @@protoc_insertion_point(field_get:PyModuleProt.DataPacket.some_sensor)
  return _internal_some_sensor();
}
inline void DataPacket::_internal_set_some_sensor(int32_t value) {
  
  _impl_.some_sensor_ = value;
}
inline void DataPacket::set_some_sensor(int32_t value) {
  _internal_set_some_sensor(value);
  // @@protoc_insertion_point(field_set:PyModuleProt.DataPacket.some_sensor)
}

// -------------------------------------------------------------------

// SendCommand

// .PyModuleProt.Command command = 1;
inline void SendCommand::clear_command() {
  _impl_.command_ = 0;
}
inline ::PyModuleProt::Command SendCommand::_internal_command() const {
  return static_cast< ::PyModuleProt::Command >(_impl_.command_);
}
inline ::PyModuleProt::Command SendCommand::command() const {
  // @@protoc_insertion_point(field_get:PyModuleProt.SendCommand.command)
  return _internal_command();
}
inline void SendCommand::_internal_set_command(::PyModuleProt::Command value) {
  
  _impl_.command_ = value;
}
inline void SendCommand::set_command(::PyModuleProt::Command value) {
  _internal_set_command(value);
  // @@protoc_insertion_point(field_set:PyModuleProt.SendCommand.command)
}

// optional int32 value = 2;
inline bool SendCommand::_internal_has_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SendCommand::has_value() const {
  return _internal_has_value();
}
inline void SendCommand::clear_value() {
  _impl_.value_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline int32_t SendCommand::_internal_value() const {
  return _impl_.value_;
}
inline int32_t SendCommand::value() const {
  // @@protoc_insertion_point(field_get:PyModuleProt.SendCommand.value)
  return _internal_value();
}
inline void SendCommand::_internal_set_value(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.value_ = value;
}
inline void SendCommand::set_value(int32_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:PyModuleProt.SendCommand.value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace PyModuleProt

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::PyModuleProt::Command> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PyModuleProt::Command>() {
  return ::PyModuleProt::Command_descriptor();
}
template <> struct is_proto_enum< ::PyModuleProt::State> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PyModuleProt::State>() {
  return ::PyModuleProt::State_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PyModuleProt_2eproto
