# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EEGProt.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rEEGProt.proto\x12\x07\x45\x45GProt\"i\n\nDataPacket\x12\x1d\n\x05state\x18\x01 \x01(\x0e\x32\x0e.EEGProt.State\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x1b\n\x04type\x18\x04 \x01(\x0e\x32\r.EEGProt.Type\"L\n\x0bSendCommand\x12!\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x10.EEGProt.Command\x12\x11\n\x04\x64\x61ta\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_data*\x7f\n\x07\x43ommand\x12\x10\n\x0c\x43OMMAND_NOOP\x10\x00\x12\x18\n\x14\x43OMMAND_START_STREAM\x10\x01\x12\x17\n\x13\x43OMMAND_STOP_STREAM\x10\x02\x12\x18\n\x14\x43OMMAND_LOAD_PROFILE\x10\x03\x12\x15\n\x11\x43OMMAND_GET_STATE\x10\x04*P\n\x05State\x12\x0e\n\nSTATE_IDLE\x10\x00\x12\x13\n\x0fSTATE_STREAMING\x10\x01\x12\x11\n\rSTATE_WAITING\x10\x02\x12\x0f\n\x0bSTATE_READY\x10\x03*9\n\x04Type\x12\r\n\tTYPE_NONE\x10\x00\x12\r\n\tTYPE_DATA\x10\x01\x12\x13\n\x0fTYPE_STATE_ONLY\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EEGProt_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMAND._serialized_start=211
  _COMMAND._serialized_end=338
  _STATE._serialized_start=340
  _STATE._serialized_end=420
  _TYPE._serialized_start=422
  _TYPE._serialized_end=479
  _DATAPACKET._serialized_start=26
  _DATAPACKET._serialized_end=131
  _SENDCOMMAND._serialized_start=133
  _SENDCOMMAND._serialized_end=209
# @@protoc_insertion_point(module_scope)
