# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MovingheadProt.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14MovingheadProt.proto\x12\x0eMovingheadProt\"E\n\nDataPacket\x12$\n\x05state\x18\x01 \x01(\x0e\x32\x15.MovingheadProt.State\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"U\n\x0bSendCommand\x12(\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x17.MovingheadProt.Command\x12\x12\n\x05value\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_value*\xa5\x01\n\x07\x43ommand\x12\x10\n\x0c\x43OMMAND_NOOP\x10\x00\x12\x16\n\x12\x43OMMAND_MOVE_RIGHT\x10\x01\x12\x15\n\x11\x43OMMAND_MOVE_LEFT\x10\x02\x12\x13\n\x0f\x43OMMAND_MOVE_UP\x10\x03\x12\x15\n\x11\x43OMMAND_MOVE_DOWN\x10\x04\x12\x17\n\x13\x43OMMAND_MOVE_NORMAL\x10\x05\x12\x14\n\x10\x43OMMAND_SET_STEP\x10\x06*=\n\x05State\x12\x0e\n\nSTATE_IDLE\x10\x00\x12\x13\n\x0fSTATE_STREAMING\x10\x01\x12\x0f\n\x0bSTATE_ERROR\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MovingheadProt_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMAND._serialized_start=199
  _COMMAND._serialized_end=364
  _STATE._serialized_start=366
  _STATE._serialized_end=427
  _DATAPACKET._serialized_start=40
  _DATAPACKET._serialized_end=109
  _SENDCOMMAND._serialized_start=111
  _SENDCOMMAND._serialized_end=196
# @@protoc_insertion_point(module_scope)
