# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ShimmersensorProt.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ShimmersensorProt.proto\x12\x11ShimmersensorProt\"\x84\x01\n\nDataPacket\x12\'\n\x05state\x18\x01 \x01(\x0e\x32\x18.ShimmersensorProt.State\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x12\n\naccel_ln_x\x18\x03 \x01(\x05\x12\x12\n\naccel_ln_y\x18\x04 \x01(\x05\x12\x12\n\naccel_ln_z\x18\x05 \x01(\x05\"X\n\x0bSendCommand\x12+\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x1a.ShimmersensorProt.Command\x12\x12\n\x05value\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_value*N\n\x07\x43ommand\x12\x10\n\x0c\x43OMMAND_NOOP\x10\x00\x12\x18\n\x14\x43OMMAND_START_STREAM\x10\x01\x12\x17\n\x13\x43OMMAND_STOP_STREAM\x10\x02*=\n\x05State\x12\x0e\n\nSTATE_IDLE\x10\x00\x12\x13\n\x0fSTATE_STREAMING\x10\x01\x12\x0f\n\x0bSTATE_ERROR\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ShimmersensorProt_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMAND._serialized_start=271
  _COMMAND._serialized_end=349
  _STATE._serialized_start=351
  _STATE._serialized_end=412
  _DATAPACKET._serialized_start=47
  _DATAPACKET._serialized_end=179
  _SENDCOMMAND._serialized_start=181
  _SENDCOMMAND._serialized_end=269
# @@protoc_insertion_point(module_scope)
